import { UserProfile, Verification, ProfilePhotos, MaritalStatus, JobCategory, PetInfo, PetSize, PetTemperament, BirthInfo, getZodiacAnimal, getFiveElement } from './types';

const AVATAR_COLORS = [
  '#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4',
  '#FFEAA7', '#DDA0DD', '#98D8C8', '#F7DC6F',
  '#BB8FCE', '#85C1E9', '#F1948A', '#82E0AA',
];

function getAvatarUrl(name: string, index: number): string {
  return `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${AVATAR_COLORS[index % AVATAR_COLORS.length].slice(1)}&color=fff&size=200&bold=true`;
}

// 인증 완료 상태
const VERIFIED_ALL: Verification = {
  identity: 'verified', maritalStatus: 'verified', job: 'verified',
  education: 'verified', photo: 'verified', income: 'verified',
};
const VERIFIED_BASIC: Verification = {
  identity: 'verified', maritalStatus: 'verified', job: 'verified',
  education: 'none', photo: 'verified', income: 'none',
};
const VERIFIED_PARTIAL: Verification = {
  identity: 'verified', maritalStatus: 'verified', job: 'pending',
  education: 'none', photo: 'verified', income: 'none',
};

function makePhotos(name: string, idx: number): ProfilePhotos {
  const base = getAvatarUrl(name, idx);
  return { main: base, face: base, body: base, additional: [] };
}

export const mockUsers: UserProfile[] = [
  {
    id: 'user_m1', name: '김민준', age: 29, gender: 'male', region: 'seoul',
    mbti: 'ENFP', education: 'bachelor',
    jobCategory: 'it_tech', job: '소프트웨어 개발자',
    income: '5000_7000',
    hobbies: ['coding', 'gaming', 'hiking', 'photography'],
    introduction: '개발과 여행을 사랑하는 개발자입니다. 주말에는 산에 가거나 카페에서 사이드 프로젝트를 합니다.',
    drinking: 'sometimes', smoking: 'no',
    birthInfo: { year: 1997, month: 3, day: 15, calendarType: "solar" as const, birthHour: 14 },
    pet: { hasPet: false, petType: "none", petFriendly: true },
    snsProfiles: [{ platform: 'instagram', url: 'https://instagram.com/minjun_dev' }],
    matchType: 'general', maritalStatus: 'single',
    verification: VERIFIED_ALL,
    photos: makePhotos('김민준', 0),
    profileImage: '', createdAt: '2026-03-01',
  },
  {
    id: 'user_f1', name: '이서연', age: 27, gender: 'female', region: 'seoul',
    mbti: 'INFJ', education: 'master',
    jobCategory: 'creative', job: 'UX 디자이너',
    income: '5000_7000',
    hobbies: ['art', 'reading', 'yoga', 'travel'],
    introduction: '디자인과 예술에 관심이 많아요. 조용하지만 깊은 대화를 좋아합니다.',
    drinking: 'sometimes', smoking: 'no',
    birthInfo: { year: 1999, month: 8, day: 22, calendarType: "solar" as const, birthHour: 9 },
    pet: { hasPet: true, petType: "cat", petName: "루나", petSize: "small", petTemperament: "independent", breed: "러시안블루", petFriendly: true },
    snsProfiles: [{ platform: 'instagram', url: 'https://instagram.com/seoyeon_ux' }],
    matchType: 'general', maritalStatus: 'single',
    verification: VERIFIED_ALL,
    photos: makePhotos('이서연', 1),
    profileImage: '', createdAt: '2026-03-02',
  },
  {
    id: 'user_m2', name: '박지훈', age: 32, gender: 'male', region: 'gyeonggi',
    mbti: 'ENTJ', education: 'bachelor',
    jobCategory: 'business', job: '마케팅 매니저',
    income: '7000_10000',
    hobbies: ['fitness', 'wine', 'travel', 'cooking'],
    introduction: '열정적으로 일하고, 열정적으로 놀아요. 좋은 와인과 여행을 즐깁니다.',
    drinking: 'often', smoking: 'no',
    birthInfo: { year: 1994, month: 1, day: 7, calendarType: "lunar" as const, birthHour: 6 },
    pet: { hasPet: false, petType: "none", petFriendly: true },
    snsProfiles: [{ platform: 'threads', url: 'https://threads.net/@jihun_park' }],
    matchType: 'general', maritalStatus: 'single',
    verification: VERIFIED_ALL,
    photos: makePhotos('박지훈', 2),
    profileImage: '', createdAt: '2026-03-03',
  },
  {
    id: 'user_f2', name: '최수아', age: 30, gender: 'female', region: 'seoul',
    mbti: 'ENFJ', education: 'bachelor',
    jobCategory: 'education', job: '초등학교 교사',
    income: '3000_5000',
    hobbies: ['reading', 'volunteering', 'baking', 'dance'],
    introduction: '아이들과 함께하는 시간이 가장 행복해요. 주말에는 베이킹하며 힐링합니다.',
    drinking: 'none', smoking: 'no',
    birthInfo: { year: 1996, month: 11, day: 3, calendarType: "solar" as const },
    pet: { hasPet: false, petType: "none", petFriendly: true },
    snsProfiles: [{ platform: 'facebook', url: 'https://facebook.com/sua.choi' }],
    matchType: 'general', maritalStatus: 'single',
    verification: VERIFIED_ALL,
    photos: makePhotos('최수아', 3),
    profileImage: '', createdAt: '2026-03-04',
  },
  {
    id: 'user_m3', name: '정우성', age: 35, gender: 'male', region: 'busan',
    mbti: 'ISTP', education: 'bachelor',
    jobCategory: 'engineering', job: '건축사',
    income: '7000_10000',
    hobbies: ['photography', 'camping', 'running', 'music'],
    introduction: '부산 바다를 사랑하는 건축사입니다. 자연 속에서 캠핑하며 여유를 즐깁니다.',
    drinking: 'sometimes', smoking: 'quit',
    birthInfo: { year: 1991, month: 5, day: 28, calendarType: "solar" as const, birthHour: 22 },
    pet: { hasPet: true, petType: "dog", petName: "바다", petSize: "large", petTemperament: "active", breed: "리트리버", petFriendly: true },
    snsProfiles: [{ platform: 'instagram', url: 'https://instagram.com/woosung_archi' }],
    matchType: 'general', maritalStatus: 'single',
    verification: VERIFIED_BASIC,
    photos: makePhotos('정우성', 4),
    profileImage: '', createdAt: '2026-03-05',
  },
  {
    id: 'user_f3', name: '한예진', age: 28, gender: 'female', region: 'busan',
    mbti: 'ESFP', education: 'bachelor',
    jobCategory: 'media', job: '방송 PD',
    income: '5000_7000',
    hobbies: ['dance', 'travel', 'movie', 'pets'],
    introduction: '에너지 넘치는 PD입니다! 새로운 경험을 사랑하고, 반려견 콩이와 함께 살아요.',
    drinking: 'sometimes', smoking: 'no',
    birthInfo: { year: 1998, month: 7, day: 14, calendarType: "solar" as const, birthHour: 11 },
    pet: { hasPet: true, petType: "dog", petName: "콩이", petSize: "small", petTemperament: "playful", breed: "포메라니안", petFriendly: true },
    snsProfiles: [{ platform: 'instagram', url: 'https://instagram.com/yejin_pd' }],
    matchType: 'general', maritalStatus: 'single',
    verification: VERIFIED_ALL,
    photos: makePhotos('한예진', 5),
    profileImage: '', createdAt: '2026-03-06',
  },
  {
    id: 'user_m4', name: '윤도현', age: 31, gender: 'male', region: 'seoul',
    mbti: 'INFP', education: 'master',
    jobCategory: 'creative', job: '작곡가',
    income: '3000_5000',
    hobbies: ['music', 'reading', 'art', 'camping'],
    introduction: '음악으로 이야기하는 사람입니다. 조용한 카페와 숲을 좋아합니다.',
    drinking: 'sometimes', smoking: 'no',
    birthInfo: { year: 1995, month: 12, day: 1, calendarType: "lunar" as const },
    pet: { hasPet: true, petType: "cat", petName: "모카", petSize: "small", petTemperament: "calm", breed: "스코티시폴드", petFriendly: true },
    snsProfiles: [{ platform: 'threads', url: 'https://threads.net/@dohyun_music' }],
    matchType: 'general', maritalStatus: 'single',
    verification: VERIFIED_BASIC,
    photos: makePhotos('윤도현', 6),
    profileImage: '', createdAt: '2026-03-07',
  },
  {
    id: 'user_f4', name: '송하은', age: 26, gender: 'female', region: 'incheon',
    mbti: 'ENTP', education: 'bachelor',
    jobCategory: 'it_tech', job: '스타트업 기획자',
    income: '3000_5000',
    hobbies: ['coding', 'travel', 'wine', 'photography'],
    introduction: '아이디어가 넘치는 기획자! 스타트업 생태계에서 살고 있어요.',
    drinking: 'sometimes', smoking: 'no',
    birthInfo: { year: 2000, month: 4, day: 19, calendarType: "solar" as const, birthHour: 16 },
    pet: { hasPet: false, petType: "none", petFriendly: true },
    snsProfiles: [{ platform: 'instagram', url: 'https://instagram.com/haeun_plan' }],
    matchType: 'general', maritalStatus: 'single',
    verification: VERIFIED_ALL,
    photos: makePhotos('송하은', 7),
    profileImage: '', createdAt: '2026-03-08',
  },
  {
    id: 'user_m5', name: '강현우', age: 34, gender: 'male', region: 'daejeon',
    mbti: 'ESTJ', education: 'doctorate',
    jobCategory: 'research', job: '연구원 (KAIST)',
    income: '5000_7000',
    hobbies: ['running', 'reading', 'cooking', 'volunteering'],
    introduction: 'KAIST 출신 연구원입니다. 체계적이고 성실한 성격이에요.',
    drinking: 'none', smoking: 'no',
    birthInfo: { year: 1992, month: 9, day: 8, calendarType: "solar" as const, birthHour: 3 },
    pet: { hasPet: false, petType: "none", petFriendly: false },
    snsProfiles: [{ platform: 'facebook', url: 'https://facebook.com/hyunwoo.kang' }],
    matchType: 'general', maritalStatus: 'single',
    verification: VERIFIED_ALL,
    photos: makePhotos('강현우', 8),
    profileImage: '', createdAt: '2026-03-09',
  },
  {
    id: 'user_f5', name: '임채원', age: 29, gender: 'female', region: 'daegu',
    mbti: 'ISFJ', education: 'bachelor',
    jobCategory: 'medical', job: '간호사',
    income: '3000_5000',
    hobbies: ['yoga', 'baking', 'pets', 'hiking'],
    introduction: '사람을 돌보는 일이 천직이에요. 따뜻하고 배려심 있는 사람을 만나고 싶어요.',
    drinking: 'none', smoking: 'no',
    birthInfo: { year: 1997, month: 2, day: 25, calendarType: "lunar" as const, birthHour: 7 },
    pet: { hasPet: true, petType: "dog", petName: "뭉치", petSize: "small", petTemperament: "playful", breed: "말티즈", petFriendly: true },
    snsProfiles: [{ platform: 'instagram', url: 'https://instagram.com/chaewon_nurse' }],
    matchType: 'general', maritalStatus: 'single',
    verification: VERIFIED_ALL,
    photos: makePhotos('임채원', 9),
    profileImage: '', createdAt: '2026-03-10',
  },
  // === 재혼 매칭 사용자 (이혼 확인 필수) ===
  {
    id: 'user_rm1', name: '이재혁', age: 40, gender: 'male', region: 'seoul',
    mbti: 'ISTJ', education: 'bachelor',
    jobCategory: 'finance', job: '회계사',
    income: '7000_10000',
    hobbies: ['hiking', 'reading', 'cooking', 'music'],
    introduction: '안정적인 삶을 추구하는 회계사입니다. 진심으로 함께할 분을 찾습니다.',
    drinking: 'sometimes', smoking: 'no',
    birthInfo: { year: 1986, month: 6, day: 12, calendarType: "solar" as const, birthHour: 10 },
    pet: { hasPet: false, petType: "none", petFriendly: true },
    snsProfiles: [],
    matchType: 'remarriage', maritalStatus: 'divorced',
    verification: VERIFIED_ALL,
    photos: makePhotos('이재혁', 10),
    remarriageInfo: {
      divorceConfirmed: true, divorceAgreementSigned: true,
      hasChildren: true, childrenCount: 1, hasCustody: true,
    },
    profileImage: '', createdAt: '2026-03-11',
  },
  {
    id: 'user_rf1', name: '박은정', age: 37, gender: 'female', region: 'gyeonggi',
    mbti: 'ESFJ', education: 'bachelor',
    jobCategory: 'medical', job: '약사',
    income: '7000_10000',
    hobbies: ['yoga', 'travel', 'cooking', 'volunteering'],
    introduction: '따뜻한 가정을 다시 꾸리고 싶어요. 서로 배려하며 함께 성장하고 싶습니다.',
    drinking: 'none', smoking: 'no',
    birthInfo: { year: 1989, month: 10, day: 30, calendarType: "solar" as const },
    pet: { hasPet: true, petType: "dog", petName: "해피", petSize: "small", petTemperament: "active", breed: "비숑", petFriendly: true },
    snsProfiles: [{ platform: 'facebook', url: 'https://facebook.com/eunjeong.park' }],
    matchType: 'remarriage', maritalStatus: 'divorced',
    verification: VERIFIED_ALL,
    photos: makePhotos('박은정', 11),
    remarriageInfo: {
      divorceConfirmed: true, divorceAgreementSigned: true,
      hasChildren: true, childrenCount: 2, hasCustody: true,
    },
    profileImage: '', createdAt: '2026-03-12',
  },
  {
    id: 'user_rm2', name: '김태호', age: 42, gender: 'male', region: 'seoul',
    mbti: 'ENFJ', education: 'master',
    jobCategory: 'legal', job: '변호사',
    income: 'over_10000',
    hobbies: ['wine', 'travel', 'art', 'running'],
    introduction: '인생 2막을 함께할 든든한 파트너를 찾고 있습니다.',
    drinking: 'sometimes', smoking: 'no',
    birthInfo: { year: 1984, month: 3, day: 5, calendarType: "lunar" as const, birthHour: 20 },
    pet: { hasPet: false, petType: "none", petFriendly: true },
    snsProfiles: [],
    matchType: 'remarriage', maritalStatus: 'divorced',
    verification: VERIFIED_ALL,
    photos: makePhotos('김태호', 0),
    remarriageInfo: {
      divorceConfirmed: true, divorceAgreementSigned: true,
      hasChildren: false,
    },
    profileImage: '', createdAt: '2026-03-13',
  },
  {
    id: 'user_rf2', name: '조미래', age: 38, gender: 'female', region: 'seoul',
    mbti: 'INFP', education: 'bachelor',
    jobCategory: 'creative', job: '플로리스트',
    income: '3000_5000',
    hobbies: ['art', 'photography', 'camping', 'pets'],
    introduction: '꽃처럼 아름다운 두 번째 사랑을 꿈꿉니다. 예술적인 감성을 가진 분이면 좋겠어요.',
    drinking: 'none', smoking: 'no',
    birthInfo: { year: 1988, month: 8, day: 17, calendarType: "solar" as const, birthHour: 15 },
    pet: { hasPet: true, petType: "both", petName: "별이/달이", petSize: "medium", petTemperament: "calm", petFriendly: true },
    snsProfiles: [{ platform: 'instagram', url: 'https://instagram.com/mirae_flower' }],
    matchType: 'remarriage', maritalStatus: 'divorced',
    verification: VERIFIED_BASIC,
    photos: makePhotos('조미래', 1),
    remarriageInfo: {
      divorceConfirmed: true, divorceAgreementSigned: true,
      hasChildren: true, childrenCount: 1, hasCustody: false,
    },
    profileImage: '', createdAt: '2026-03-14',
  },
  {
    id: 'user_m6', name: '서준혁', age: 28, gender: 'male', region: 'gwangju',
    mbti: 'ESTP', education: 'bachelor',
    jobCategory: 'service', job: '요리사 (호텔)',
    income: '3000_5000',
    hobbies: ['cooking', 'fitness', 'travel', 'dance'],
    introduction: '맛있는 음식으로 행복을 전하는 셰프입니다. 활동적인 성격이에요!',
    drinking: 'often', smoking: 'no',
    birthInfo: { year: 1998, month: 1, day: 23, calendarType: "solar" as const },
    pet: { hasPet: false, petType: "none", petFriendly: true },
    snsProfiles: [{ platform: 'instagram', url: 'https://instagram.com/chef_junhyuk' }],
    matchType: 'general', maritalStatus: 'single',
    verification: VERIFIED_BASIC,
    photos: makePhotos('서준혁', 2),
    profileImage: '', createdAt: '2026-03-15',
  },
  {
    id: 'user_f6', name: '김소희', age: 25, gender: 'female', region: 'seoul',
    mbti: 'INTJ', education: 'bachelor',
    jobCategory: 'it_tech', job: '데이터 분석가',
    income: '5000_7000',
    hobbies: ['coding', 'reading', 'fitness', 'movie'],
    introduction: '논리적이지만 로맨틱한 면도 있어요. 지적인 대화를 즐깁니다.',
    drinking: 'sometimes', smoking: 'no',
    birthInfo: { year: 2001, month: 6, day: 9, calendarType: "solar" as const, birthHour: 12 },
    pet: { hasPet: false, petType: "none", petFriendly: false },
    snsProfiles: [{ platform: 'threads', url: 'https://threads.net/@sohee_data' }],
    matchType: 'general', maritalStatus: 'single',
    verification: VERIFIED_ALL,
    photos: makePhotos('김소희', 3),
    profileImage: '', createdAt: '2026-03-16',
  },
  {
    id: 'user_m7', name: '오승민', age: 33, gender: 'male', region: 'seoul',
    mbti: 'ISFP', education: 'bachelor',
    jobCategory: 'media', job: '영상 감독',
    income: '5000_7000',
    hobbies: ['photography', 'movie', 'music', 'travel'],
    introduction: '영상으로 이야기를 만드는 감독입니다. 감성적인 사람을 좋아해요.',
    drinking: 'sometimes', smoking: 'no',
    birthInfo: { year: 1993, month: 11, day: 14, calendarType: "lunar" as const, birthHour: 8 },
    pet: { hasPet: true, petType: "dog", petName: "초코", petSize: "medium", petTemperament: "playful", breed: "웰시코기", petFriendly: true },
    snsProfiles: [{ platform: 'instagram', url: 'https://instagram.com/director_oh' }],
    matchType: 'general', maritalStatus: 'single',
    verification: VERIFIED_PARTIAL,
    photos: makePhotos('오승민', 4),
    profileImage: '', createdAt: '2026-03-17',
  },
  {
    id: 'user_f7', name: '정다은', age: 31, gender: 'female', region: 'gyeonggi',
    mbti: 'ESTJ', education: 'master',
    jobCategory: 'finance', job: '금융 컨설턴트',
    income: '7000_10000',
    hobbies: ['fitness', 'wine', 'travel', 'running'],
    introduction: '커리어와 사랑 모두 잡고 싶은 욕심쟁이. 함께 성장할 파트너를 원해요.',
    drinking: 'sometimes', smoking: 'no',
    birthInfo: { year: 1995, month: 4, day: 2, calendarType: "solar" as const, birthHour: 18 },
    pet: { hasPet: false, petType: "none", petFriendly: true },
    snsProfiles: [{ platform: 'instagram', url: 'https://instagram.com/daeun_finance' }],
    matchType: 'general', maritalStatus: 'single',
    verification: VERIFIED_ALL,
    photos: makePhotos('정다은', 5),
    profileImage: '', createdAt: '2026-03-18',
  },
  {
    id: 'user_rm3', name: '최동훈', age: 45, gender: 'male', region: 'gyeonggi',
    mbti: 'ESFP', education: 'bachelor',
    jobCategory: 'self_employed', job: '자영업 (카페 운영)',
    income: '5000_7000',
    hobbies: ['cooking', 'music', 'pets', 'camping'],
    introduction: '카페를 운영하며 소소한 행복을 찾고 있어요. 따뜻한 분을 만나고 싶습니다.',
    drinking: 'sometimes', smoking: 'no',
    birthInfo: { year: 1981, month: 7, day: 21, calendarType: "solar" as const },
    pet: { hasPet: true, petType: "dog", petName: "보리", petSize: "large", petTemperament: "active", breed: "진돗개", petFriendly: true },
    snsProfiles: [{ platform: 'instagram', url: 'https://instagram.com/cafe_donghun' }],
    matchType: 'remarriage', maritalStatus: 'divorced',
    verification: VERIFIED_ALL,
    photos: makePhotos('최동훈', 6),
    remarriageInfo: {
      divorceConfirmed: true, divorceAgreementSigned: true,
      hasChildren: true, childrenCount: 2, hasCustody: false,
    },
    profileImage: '', createdAt: '2026-03-19',
  },
  {
    id: 'user_rf3', name: '신혜민', age: 36, gender: 'female', region: 'incheon',
    mbti: 'ENFP', education: 'bachelor',
    jobCategory: 'education', job: '유치원 원장',
    income: '5000_7000',
    hobbies: ['dance', 'baking', 'volunteering', 'travel'],
    introduction: '긍정적인 에너지로 가득한 사람이에요. 새로운 시작을 함께할 분 찾아요!',
    drinking: 'none', smoking: 'no',
    birthInfo: { year: 1990, month: 12, day: 10, calendarType: "lunar" as const, birthHour: 5 },
    pet: { hasPet: false, petType: "none", petFriendly: true },
    snsProfiles: [{ platform: 'facebook', url: 'https://facebook.com/hyemin.shin' }],
    matchType: 'remarriage', maritalStatus: 'divorced',
    verification: VERIFIED_ALL,
    photos: makePhotos('신혜민', 7),
    remarriageInfo: {
      divorceConfirmed: true, divorceAgreementSigned: true,
      hasChildren: true, childrenCount: 1, hasCustody: true,
    },
    profileImage: '', createdAt: '2026-03-20',
  },
];

// Compute zodiac and five elements
mockUsers.forEach((user) => {
  user.birthInfo.zodiacAnimal = getZodiacAnimal(user.birthInfo.year);
  user.birthInfo.fiveElement = getFiveElement(user.birthInfo.year);
});

// Set profile images from photos
mockUsers.forEach((user, index) => {
  const url = getAvatarUrl(user.name, index);
  user.profileImage = url;
  user.photos.main = url;
  user.photos.face = url;
  user.photos.body = url;
});
